import type { i18n as I18nInstance } from 'i18next';

import workbookStringToKey from './generated/workbookStringToKey.json';

const stringToTranslationKey = workbookStringToKey as Record<string, string>;

/**
 * Resolve a workbook / dump string to the correct locale using `workbookLabels`.
 * Keys and Swedish values are generated by `tools/generate_workbook_labels.py`.
 */
export function translateWorkbookString(raw: string, i18n: I18nInstance): string {
  const trimmed = raw.trimStart();
  if (trimmed.startsWith('=')) {
    return raw;
  }
  const key = stringToTranslationKey[raw];
  if (!key) {
    return raw;
  }
  return String(i18n.t(key, { ns: 'workbookLabels' }));
}
